spring:
  application:
    name: JOVA-server-V1
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      pool-name: HikariPool
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 30000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
    properties:
        hibernate:
            dialect: org.hibernate.dialect.MariaDBDialect
            format_sql: true
            use_sql_comments: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  logging:
    level:
      root: INFO
      org.springframework.web: INFO
    file:
      path: ./logs/application.log
    pattern:
      console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} -%kvp- %msg%n"
  data:
    jdbc:
      dialect: mysql
jwt:
  secret: ${JWT_SECRET}
gauth:
  security:
    client-id: ${GAUTH_CLIENT_ID}
    client-secret: ${GAUTH_CLIENT_SECRET}
    redirect-uri: ${GAUTH_REDIRECT_URI}
