spring:
  application:
    name: JOVA-server-V1
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
    properties:
        hibernate:
            dialect: org.hibernate.dialect.MySQLDialect
            format_sql: true
            use_sql_comments: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  logging:
    level:
      root: INFO
      org.springframework.web: DEBUG
    file:
      path: ./logs/application.log
  data:
    jdbc:
      dialect: mysql
jwt:
  secret: ${JWT_SECRET}
gauth:
  security:
    client-id: ${GAUTH_CLIENT_ID}
    client-secret: ${GAUTH_CLIENT_SECRET}
    redirect-uri: ${GAUTH_REDIRECT_URI}